plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.16'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.otboo'
version = '0.0.1-SNAPSHOT'
description = 'Personalized outfit recommendation service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// Real-time communication
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// Cache
	implementation 'org.springframework.boot:spring-boot-starter-cache'

	// Database
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'org.postgresql:postgresql'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Spring Batch
	implementation 'org.springframework.boot:spring-boot-starter-batch'

	// Configuration metadata
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.springframework.batch:spring-batch-test'

	// Test database
	testRuntimeOnly 'com.h2database:h2'

	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()

	// 테스트 완료 후 커버리지 보고서 생성
	finalizedBy tasks.named('jacocoTestReport')
}

tasks.named('jacocoTestReport') {
	dependsOn tasks.named('test')

	reports {
		html.required = true
		xml.required = true
		csv.required = false
	}
}