spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:otboo}
    username: ${DB_USERNAME:otboo}
    password: ${DB_PASSWORD:otboo}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  batch:
    jdbc:
      initialize-schema: always

jwt:
  secret: ${JWT_SECRET:3WayDafV59YynmTwCpaDtnpeur8sokrAkQ+wFlXO4QY=}
  access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  websocket:
    allowed-origin-patterns: ${WEBSOCKET_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,http://localhost:3000,http://localhost:8080}


kakao:
  local:
    api-key: ${KAKAO_REST_API_KEY:kakao-rest-api-key}
    base-url: https://dapi.kakao.com